[package]
name = "os"
version = "0.1.0"
authors = ["Yifan Wu <shinbokuow@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
buddy_system_allocator = "0.6"
bitflags = "1.2.1"
xmas-elf = "0.7.0"
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers", rev = "61ece50" }
easy-fs = { path = "../easy-fs" }
ext4 = { path = "../ext4" }
log = "0.4"
sbi-rt = { version = "0.0.2", features = ["legacy"] }
spin = "0.7.0"
volatile = "0.3"
vfs-defs = { path = "../vfs-defs" }
vfs = { path = "../vfs" }
device = { path = "../device" }
crate_interface = { git = "https://github.com/Byte-OS/crate_interface.git" }
arch = { path = "arch", features = ["kcontext"]}
fdt = "0.1.5"

logger = { path = "../logger" }

[profile.release]
debug = true
opt-level = 0
